project:
  type: website

website:
  title: "test-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - new-page.qmd
      - about.qmd

format:
  html:
    theme:
      - solar
      - brand
    css: styles.css
    toc: true

editor: visual

